.\" Manpage for nuseradd.
.\" Contact mateus.schroeder@gmail.com to correct errors or typos.
.TH man 1 "1 may 2019" "0.01" "Magical matrix man page"
.SH NAME
Magical Matrix \- Mathematical program used to resolve calculate matrix product, and another matrix functions. 
.SH SYNOPSIS
magical-matrix [USERNAME]
.SH DESCRIPTION
Magical Matrix is facilitator for finding results by numerical calculus.
.SH OPTIONS
NTZ - Numerical theory (integer/Zahlen) mode: the program will start receiving all variables as Integers .
.br
NTZ - Numerical theory (Natural) mode: the program will start receiving all variables as Natural.
.br
NT - Numerical theory mode: the same as <NTZ>.
.br
NC - Numerical calculus mode: the program will receive all variables as Real (long double) and will approximate the results.
.br
A - Algebra mode: (still not implemented).
.br
.SH BUGS
No known bugs. If any, please report it on github
.SH AUTHOR
Mateus Schroeder da Silva (mateus.schroeder@gmail.com
